repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: ['--remove']
    -   id: name-tests-test
        args: ['--django']
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.1.3'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
