version: '3.4'

services:
  turplanlegger-api:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
      args:
        - DATABASE_URI=${DATABASE_URI:-postgresql://turadm:passord@turplanlegger-db:5432/turplanlegger?connect_timeout=10&application_name=turplanleggerapi}
        - BASE_URL=${BASE_URL:-turplanlegger-api}
        - SECRET_KEY=${SECRET_KEY:-hemmelig}
        - SECRET_KEY_ID=${SECRET_KEY_ID:-1}
    container_name: turplanlegger-dev
    depends_on:
      - turplanlegger-db
    links:
      - turplanlegger-db

  turplanlegger-db:
    image: postgres:15.2
    container_name: turplanlegger-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=turadm
      - POSTGRES_PASSWORD=passord
      - POSTGRES_DB=turplanlegger
