FROM ubuntu:23.04

ARG DEBIAN_FRONTEND=noninteractive
ARG DATABASE_URI=postgresql://turadm:passord@turplanlegger_postgres:5432/turplanlegger?connect_timeout=10&application_name=turplanleggerapi
ARG BASE_URL=localhost
ARG SECRET_KEY=hemmelig
ARG SECRET_KEY_ID=1
ARG POSTGRES_DB=turplanlegger

RUN apt-get -y update && apt-get install -y \
    build-essential \
    python3.10-dev \
    python3-pip \
    postgresql-14 \
    libpq-dev

WORKDIR /turplanlegger

ADD requirements.txt /app/requirements.txt
ADD requirements-prod.txt /app/requirements-prod.txt

RUN pip3 install -r /app/requirements.txt -r /app/requirements-prod.txt

RUN mkdir /etc/turplanlegger && touch /etc/turplanlegger/turplanlegger.conf

RUN echo "DATABASE_URI=\"$DATABASE_URI\"" >> /etc/turplanlegger/turplanlegger.conf && \
 echo "DATABASE_NAME=\"$POSTGRES_DB\"" >> /etc/turplanlegger/turplanlegger.conf && \
 echo 'DATABASE_MAX_RETRIES=5' >> /etc/turplanlegger/turplanlegger.conf && \
 echo "SECRET_KEY=\"$SECRET_KEY\"" >> /etc/turplanlegger/turplanlegger.conf && \
 echo "SECRET_KEY_ID=\"$SECRET_KEY_ID\"" >> /etc/turplanlegger/turplanlegger.conf && \
 echo "BASE_URL=\"$BASE_URL\"" >> /etc/turplanlegger/turplanlegger.conf
