version: '3.3'
services:
  flask:
    build: .
    container_name: turplanlegger
    command: 'python3 -m unittest discover tests'
    ports:
      - '80:8080'
    volumes:
      - ./:/turplanlegger
    depends_on:
      - turplanleggerdb
    links:
      - turplanleggerdb

  turplanleggerdb:
    image: postgres:14.0
    container_name: turplanleggerdb
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
