version: '3.9'

services:
  dev-api:
    build:
      context: .
    environment:
    - TP_DATABASE_URI=${TP_DATABASE_URI:-postgresql://turadm:passord@turplanlegger-dev-db:5432/turplanlegger?connect_timeout=10&application_name=turplanlegger-api}
    - TP_DATABASE_NAME=${TP_DATABASE_NAME:-turplanlegger}
    - TP_DATABASE_MAX_RETRIES=${TP_DATABASE_MAX_RETRIES:-2}
    - TP_DATABASE_MIN_POOL_SIZE=${TP_DATABASE_MIN_POOL_SIZE:-2}
    - TP_DATABASE_MAX_POOL_SIZE=${TP_DATABASE_MAX_POOL_SIZE:-10}
    - TP_DATABASE_TIMEOUT=${TP_DATABASE_TIMEOUT:-10}
    - TP_DATABASE_MAX_WAITING=${TP_DATABASE_MAX_WAITING:-0}
    - TP_DATABASE_MAX_LIFETIME=${TP_DATABASE_MAX_LIFETIME:-1800}
    - TP_DATABASE_MAX_IDLE=${TP_DATABASE_MAX_IDLE:-300}
    - TP_DATABASE_RECONNECT_TIMEOUT=${TP_DATABASE_RECONNECT_TIMEOUT:-90}
    - TP_DATABASE_CONNECTION_TEST_TIMEOUT=${TP_DATABASE_CONNECTION_TEST_TIMEOUT:-1}
    - TP_LOG_LEVEL=${TP_LOG_LEVEL:-DEBUG}
    - TP_CREATE_ADMIN_USER=${TP_CREATE_ADMIN_USER:-0}
    - TP_ADMIN_EMAIL=${TP_ADMIN_EMAIL:-test@test.com}
    - TP_ADMIN_PASSWORD=${TP_ADMIN_PASSWORD:-Changeme}
    - TP_CORS_ORIGINS=${TP_CORS_ORIGINS:-http://localhost:3000}
    - TP_AUDIENCE=${TP_AUDIENCE:-0149fc65-259e-4895-9034-e144c242f733}
    - TP_AZURE_AD_B2C_KEY_URL=${TP_AZURE_AD_B2C_KEY_URL:-https://turplanlegger.b2clogin.com/turplanlegger.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_signin}
    - TP_TOKEN_EXPIRE_TIME=${TP_TOKEN_EXPIRE_TIME:-86400}
    - TP_SECRET_KEY=secretsecret
    - TP_SECRET_KEY_ID=1234
    hostname: turplanlegger-dev-api
    restart: unless-stopped
    ports:
      - ${TP_PORT:-8080}:5000
    depends_on:
      - dev-db
    networks:
      - turplanlegger-dev-network

  dev-db:
    image: postgres:15-alpine
    hostname:  turplanlegger-dev-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    ports:
      - ${TP_POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${TP_POSTGRES_USER:-turadm}
      - POSTGRES_PASSWORD=${TP_POSTGRES_PASSWORD:-passord}
      - POSTGRES_DB=${TP_POSTGRES_DB:-turplanlegger}
    networks:
      - turplanlegger-dev-network

networks:
  turplanlegger-dev-network:
    name: turplanlegger-dev-network
