version: '3.3'
services:
  flask:
    build: .
    container_name: turplanlegger
    command: 'flask run --debugger -h 0.0.0.0 --port 8080 --with-threads --reload'
    ports:
      - '80:8080'
    volumes:
      - ./:/turplanlegger
    depends_on:
      - turplanleggerdb
    links:
      - turplanleggerdb

  turplanleggerdb:
    image: postgres:latest
    container_name: turplanleggerdb
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
