version: '3.9'

services:
  turplanlegger-api:
    build:
      context: .
    environment:
      - TP_DATABASE_URI=${TP_DATABASE_URI:-postgresql://turadm:passord@/turplanlegger?connect_timeout=10&application_name=turplanlegger-api}
      - TP_DATABASE_NAME={$TP_DATABASE_NAME:-turplanlegger}
      - TP_DATABASE_MAX_RETRIES
      - TP_SECRET_KEY
    hostname: turplanlegger-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:5000/test"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    ports:
      - '${TP_PORT:-5000}:5000'
    depends_on:
      - turplanlegger-db
    networks:
      - turplanlegger-network

  turplanlegger-db:
    image: postgres:15-alpine
    hostname:  turplanlegger-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-turadm}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-passord}
      - POSTGRES_DB=${POSTGRES_DB:-turplanlegger}
    networks:
      - turplanlegger-network

volumes:
  database:
    driver: local

networks:
  turplanlegger-network:
    name: turplanlegger-network
