version: '3.4'

services:
  turplanlegger-api:
    build:
      context: .
      dockerfile: ./test.Dockerfile
    container_name: turplanlegger-api
    depends_on:
      - turplanlegger-db
    links:
      - turplanlegger-db

  turplanlegger-db:
    image: postgres:15.0
    container_name: turplanlegger-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
