version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile-prod
      args:
        - DATABASE_URI=${DATABASE_URI:-postgresql://turadm:passord@turplanlegger_postgres:5432/turplanlegger?connect_timeout=10&application_name=turplanleggerapi}
        - BASE_URL=${BASE_URL:-localhost}
        - SECRET_KEY=${SECRET_KEY:-hemmelig}
        - SECRET_KEY_ID=${SECRET_KEY_ID:-1}
    container_name: turplanlegger-api
    command: 'uwsgi --http 0.0.0.0:5000 --module wsgi:app --processes 4 --threads 2 --stats 0.0.0.0:9191'
    ports:
      - '5000:5000'
      - '9191:9191'
      - '8080:8080'
    volumes:
      - ./:/turplanlegger
    depends_on:
      - turplanlegger_postgres
    networks:
      - turplanlegger_network

  turplanlegger_postgres:
    image: postgres:15.1
    container_name: turplanlegger-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-turadm}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-passord}
      - POSTGRES_DB=${POSTGRES_DB:-turplanlegger}
    networks:
      - turplanlegger_network

networks:
  turplanlegger_network:
    name: turplanlegger-network
