name: Code standards, unittests and docker build

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        pip install .[dev]
    - name: Lint using ruff
      run: hatch run lint
    - name: Format using ruff
      run: hatch run format

  test-postgres15:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres@sha256:8df947e4b872177cbc2d6bae01c46542631982deaf8777849decd495f3fae0be
        env:
          POSTGRES_DB: turplanlegger
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        pip install .[dev]
    - name: Test with pytest
      env:
        TP_DATABASE_URI: postgresql://postgres:postgres@localhost/turplanlegger?connect_timeout=10&application_name=turplanlegger
      run: |
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        hatch run cov >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build Docker image
      run: |
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        docker build . >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
