name: Create and publish a Github tag and release

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  check-and-publish-new-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.TURPLANLEGGER_SIGNING_BOT_APP_ID }}
          private_key: ${{ secrets.TURPLANLEGGER_SIGNING_BOT_APP_PRIVATE_KEY }}

      - name: Login for bot
        run: |
          git config user.name "turplanlegger-signing-bot[bot]"
          git config user.email "${{ secrets.TURPLANLEGGER_SIGNING_BOT_APP_ID }}+turplanlegger-signing-bot[bot]@users.noreply.github.com"

      - name: Create new tag
        env:
          NEW_VERSION: v1.0.0test
        run: |
          git checkout testing-siging-bot
          git commit --allow-empty -sm "Test"
          git push -f
#
#      - name: Update latest tag
#        run: |
#          git tag -sfam "Release v$NEW_VERSION" latest
#          git push --force --tags
#          echo "Tag \`latest\` updated to \`$NEW_VERSION\` \`$(git rev-parse -q --verify $NEW_VERSION)\`" >> $GITHUB_STEP_SUMMARY
#
#      - name: Create GitHub Release
#        uses: ncipollo/release-action@v1
#        with:
#          name: "Release ${{ env.NEW_VERSION }}"
#          tag: ${{ env.NEW_VERSION }}
#          token: ${{ secrets.DEPLOY_TOKEN }}
