# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code standards and unittests

on:
  push:
    branches: [ main , release/* ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: turplanlegger
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install .
    - name: Pre-commit hooks
      id: hooks
      run: |
        pre-commit run -a --show-diff-on-failure
    - name: Lint with flake8
      id: lint
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=50 --max-line-length=127 --statistics
    - name: Test with pytest
      id: test
      run: |
        echo 'DATABASE_HOST="localhost > /etc/turplanlegger/turplanlegger.conf'
        echo 'DATABASE_INSTANCE="turplanlegger"' >> /etc/turplanlegger/turplanlegger.conf
        echo 'DATABASE_USERNAME="postgres"' >> /etc/turplanlegger/turplanlegger.conf
        echo 'DATABASE_PASSWORD="postgres"' >> /etc/turplanlegger/turplanlegger.conf

        pytest tests/*.py
