# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code standards and unittests

on:
  push:
    branches: [ main , release/* ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: turplanlegger
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install .

    - name: Pre-commit hooks
      id: hooks
      run: |
        pre-commit run -a --show-diff-on-failure
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Test with pytest
      id: test
      run: |
        pytest tests/test_*.py --csv tests/test_result_tmp.csv --csv-columns utc_timestamp,id,module,name,file,status,message,duration
        sed 1d tests/test_result_tmp.csv >> tests/test_result.csv
        git add tests/test_result.csv
        git commit -m "Added test result"
        git push
